entities:
  mob-ai: true
  auto-spawn-tick: 400
  worlds-spawn-disabled: "lobby"

max-spawns:
  bat: 0
  blaze: 0
  cave-spider: 0
  chicken: 0
  cow: 0
  creeper: 0
  donkey: 0
  enderman: 0
  ghast: 0
  horse: 0
  ocelot: 0
  pig: 0
  rabbit: 0
  sheep: 0
  skeleton: 0
  spider: 0
  squid: 0
  witch: 0
  wolf: 0
  zombie: 0
