name: MobPlugin
main: de.kniffo80.mobplugin.MobPlugin
version: "1.0"
api: ["1.0.0"]
load: STARTUP
author: PetteriM1

commands:
  mob:
    description: ""
    aliases: ["mob"]
    usage: /mob
    permission: mobplugin.command

permissions:
  mobplugin.command:
    description: ""
    default: op
